spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/training
    sqlScriptEncoding: UTF-8
    username: root
    password:
logging:
  level:
    root: INFO
    sample:
      mybatis:
        mapper: TRACE